Added save_figures() function
platiagro/kubeflow pull request #11
Opened 2021-04-30 16:38 UTC by dnlcesilva

Added save_figures () function, to save the figures of a monitoring notebook.

2021-04-30 16:51 UTC, fberanizo requested changes

2021-04-30 16:51 UTC, fberanizo commented on components/contrib/platiagro-notebook-image/Model.py
> +            print(test)
@dnlcesilva acho que aqui fica legal usar assim no lugar do print `logging.exception("Monitoring Task Error")`:

https://stackoverflow.com/a/5191885

2021-04-30 17:00 UTC, dnlcesilva commented on components/contrib/platiagro-notebook-image/Model.py
> +            print(test)
@fberanizo tinha colocado esse print quando estávamos fazendo teste, esqueci de retirar rsrsrsr.

2021-05-04 12:06 UTC, fberanizo approved these changes

2021-05-04 12:06 UTC, merged