adding a pretty_errors library
platiagro/kubeflow pull request #58
Opened 2021-11-10 13:29 UTC by dnlcesilva

adding a pretty_errors library

2021-11-18 14:14 UTC, fberanizo requested changes

2021-11-18 14:14 UTC, fberanizo commented on components/platiagro-notebook-servers/base/Dockerfile.cpu
> +ADD sitecustomize.py /opt/conda/lib/python3.8/site-packages/sitecustomize.py
@dnlcesilva hmm este arquivo acho que é melhor adicioná-lo no `experiment/Dockerfile` e remover do `base/Dockerfile.cpu`. 
Porque aí já funciona pra imagens de CPU e GPU.

2021-11-18 14:15 UTC, dnlcesilva commented on components/platiagro-notebook-servers/base/Dockerfile.cpu
> +ADD sitecustomize.py /opt/conda/lib/python3.8/site-packages/sitecustomize.py
Vou fazer isso!

2021-11-19 11:04 UTC, fberanizo approved these changes
👍

2021-11-19 11:04 UTC, merged